# Generated by Django 2.2.7 on 2019-11-16 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
