# Generated by Django 2.2.7 on 2019-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20191116_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='on_account',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='place',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
