# Generated by Django 2.2.7 on 2019-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20191116_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('INC', 'INCOME'), ('SPE', 'SPENDINGS'), ('TEC', 'TECHNIC')], max_length=3),
        ),
    ]
